### PR TITLE
Add support for URI strings that map to Source Types

### PR DESCRIPTION
**Pull request by patricksimonian**
## URI Strings?
Mentioned in #152 

I feel like the ability to match up a source dynamically via a string would be great. The URI scheme works really well for this I find. 

Here is the API. The URI follows this scheme...

__`<SOURCE TYPE>://<source value/handle/id>?<props to pass to component dynamically>`__

The valid source types are:
- github
- facebook
- twitter
- skype
- instagram
... etc, 

You'd create a uri like: `github://patricksimonian?size=100`

## Query Params
The query params can be appended onto the string to apply props dyanmically to the `Avatar` component. I added a prop called `allowUriProps` (defaults to `true`) which can enable/disable this behaviour.

## Usage

```js
<Avatar uri="github://patricksimonian" allowUriProps={false} />

// or dynamically
// lets assume what i get back is this as data [{ service: 'facebook', id: 123123}],
const avatars = await axios.get('path to avatars')
const uris = avatars.map(a => `${a.service}://${a.id}`);

const avatars = uris.map(uri => <Avatar key="blah" uri={uri} size="100"/>)
```

### CODE REVIEW

**Comment by patricksimonian** [comment]
@Sitebase any thoughts on this?

**Comment by patricksimonian** [comment]
Just as an fyi,  ...because i need this component with the uri capability soon here...I'm going to publish a fork of this to npm. On the onset this PR is merged or a better solution is found, i'll happily unpublish :). I'm just in a bit of a time bind.

**Comment by patricksimonian** [comment]
npm package published to `@pahtaro/react-avatar` for now

**Comment by JorgenEvens** [comment]
Hi @patricksimonian,

I'll try to review this as soon as possible. I'm not really a fan as it seems this could be implemented using a wrapper component. Is there any reason why you did not implement this behavior using a higher order component and want it in core?

**Comment by patricksimonian** [comment]
Thanks for getting back to me. You know what? Slightly embarressed to say, this just never came to mind! I've been sick for the past few days and have been wfh. I really like your solution though. I'd recommend closing this PR, and ill stick with the hoc. Thanks for enlightening me on this.

**Comment by JorgenEvens** [comment]
@patricksimonian no problem! Good luck!

**Pull request closed without merging**
