### PR TITLE
Typedefs

### PR DESCRIPTION
**Pull request by iamdanthedev**
Hello gentlemen

Does it look correct?
I assumed that all the props are optional, as nothing is specified in the docs on this account

### CODE REVIEW

**Comment by iamdanthedev** [comment]
In VS Code it looks like this:

image

Even though I am working wih TS 8 hours a day, I never published typings to existing modules, but it seems to work fine

**Comment by JorgenEvens** [comment]
Awesome @iamdanthedev, I'll try and get these in tonight!

**Comment by JorgenEvens** [comment]
Great @iamdanthedev, looks good! 👍 

Could you remove the `package-lock.json` file and rebase onto the `master` branch? That should solve the CI error we are getting.

**Comment by JorgenEvens** [comment]
Thanks @iamdanthedev for your contribution, your type definitions are now available in [v3.1.1](https://github.com/Sitebase/react-avatar/releases/tag/v3.1.1) 🎉

**Pull request merged**
