### PR TITLE
add retina support to gravatar

### PR DESCRIPTION
**Pull request by RahavLussato**

### CODE REVIEW

**Comment by Sitebase** [comment]
Thanks for the PR Rahav.
I would like to suggest a small modification to your code.

Where you require the retina lib I would do the following:

```
var isRetina = require('is-retina')();
```

And in your size condition you can now use the `isRetina` variable as a regular boolean.
This way we only need to execute the the `isRetina()` function once the page loads instead of every time when a rerender happens.

Can you also mention `resolves #21` in your description. This will auto close the retina issue when I merge this.

**Comment by RahavLussato** [comment]
Done.
resolves #21

**Comment by Sitebase** [comment]
@RahavLussato I just noticed that you made the changes in the `.js` file. You should move these changes to the `.jsx` file because the `.js` file is automatically generated from the `.jsx` file when you run `grunt build`.

**Comment by RahavLussato** [comment]
Done

**Comment by RahavLussato** [comment]
@Sitebase  please rebuild it again because now on master the .js file not including the changes.

**Pull request merged**
