### PR TITLE
Fixed fetch async issue

### LINKED ISSUE #39: Show '*' when setting a letter to value prop
In some case. using avatar like this:

```xml
<Avatar value="A"/>
```

The `Avatar` will show `*` or `A` randomly. It seems caused by an async problem.

### PR DESCRIPTION
**Pull request by taoyuan**
Fixed #39

### CODE REVIEW

**Comment by Sitebase** [comment]
@taoyuan Thanks for the PR. Can you fix the failing build?

**Comment by taoyuan** [comment]
@Sitebase I have fixed the failing build just now. 😃

**Comment by RahavLussato** [comment]
@Sitebase is there any plan to merge this ?

**Comment by Sitebase** [comment]
This PR is now released as version `2.2.0`

**Comment by Sitebase** [comment]
@taoyuan @RahavLussato This PR is now released as version `2.2.0`

**Pull request merged**
