### PR TITLE
move React.PropTypes -> PropTypes

### PR DESCRIPTION
**Pull request by credli**

### CODE REVIEW

**Comment by jimmybaker** [comment]
👍 Thank you

**Comment by lostboy** [comment]
Also thanks 👍 
When do you think you could cut a new version with this? I'm so close to being 16 compatible.

**Comment by credli** [comment]
@Sitebase could you please?

**Comment by Sitebase** [comment]
@credli @jimmybaker @lostboy this one is included in version 2.4.0. Thanks for the PR

**Pull request merged**
