### PR TITLE
Add fgColor property for controlling text

### LINKED ISSUE #17: Allow specifying color of text as prop
Font color for `value` and `name` display mode is fixed to `#FFF`. I would like to set the color using a property. I can provide a PR, just let me know what name the prop should have.

### PR DESCRIPTION
**Pull request by Gertt**
Resolves #17

### CODE REVIEW

**Comment by krue-doug** [comment]
This seems like a backwards way of naming. In CSS, `color` refers to the font color, and `background-color` refers to the background.

**Comment by JorgenEvens** [comment]
Hi @krue-doug,

In hindsight that would have been a better choice, but at that point it would have broken lots of existing users' code which is not something we are looking to do.

**Comment by krue-doug** [comment]
@JorgenEvens my suggestion would be to eventually deprecate `color` and `fgColor` in favor of something more clear, such as `fontColor`, and `backgroundColor` (or `bgColor`). I would say give users a chance to migrate until the next major version change.

**Comment by JorgenEvens** [comment]
@krue-doug I'm not really interested in doing so as it would provide little benefit. I'll see what @Sitebase's opinion on the matter is.

**Pull request merged**
